# Linux/MPI Makefile for MapReduce examples, g++, MPI

CC =		gcc
CPP =		g++
CCFLAGS =	-g -O -I../src -DMPICH_IGNORE_CXX_SEEK
LINK =		g++
LINKFLAGS =	-g -O
USRLIB =	../src/libmrmpi_linux.so
SYSLIB =	-lmpich -lmpl -lpthread

include Makefile.common
