# MPI-based makefile using mpic++ and mpicc.

CC =		mpicc 
CPP =		mpic++ 
CCFLAGS =	-g -O -I../src -m64
LINK =		mpic++ -m64
LINKFLAGS =	-g -O -m64
USRLIB =	../src/libmrmpi_mac64.a
SYSLIB =

include Makefile.common
